---

stages:
  - build

variables:
  ErrorActionPreference: "Stop"

build-prod-powershell-module:
  only:
    - master
  stage: build
  script:
    - Invoke-PSDeploy -Path .\Deploy\.PSDeploy.ps1 -Tags production -Force -Verbose
  tags:
    - win-posh51-runner
  except:
    variables:
      - $CI_PROJECT_NAME == "PowerShellModule-Template"

build-test-powershell-module:
  only:
    - staging
    - test
  stage: build
  script:
    - Invoke-PSDeploy -Path .\Deploy\.PSDeploy.ps1 -Tags test -Force -Verbose
  tags:
    - win-posh51-runner
  except:
    variables:
      - $CI_PROJECT_NAME == "PowerShellModule-Template"